### ISSUE TITLE
How to handle "asserted" specimen->OTU relationships

### ISSUE THREAD

**Issue by aazaff** [paleobot/pbot_client#12]
If a user simply wants to state that a specimen belongs to a particular OTU, and does not want to enter any additional descriptive/character/state information about that particular specimen, then that is essentially the same as reporting a PBDB "occurrence". 

Perhaps pbot should not even track those types of relationships in its backend, but should redirect that entry to the Paleobiology Database?

related to #11

**Comment by aazaff** [comment]
Yup! These belong in the PBDB

**Comment by doricon** [comment]
I think we need to be able to do this in PBot. Two reasons: 
1) I don't want to have to simultaneously be entering info into PBot and PBDB when I am describing an OTU and have multiple occurrences (specimens from different localities) to record as supporting the OTU. Can this be handled as a pass-though form (forgot what this is called in computer-speak) from PBot to PBDB? 
2) For working with "private" OTUs in the user's workbench, we won't have a way to assign specimens to that OTU through PBDB until the OTU becomes "published" (and thus visible to PBDB). 

Additional thought: If I am downloading data from PBot, In some cases I will want to know about all the specimens/occurrence records of an OTU. If it is only entered through PBDB, will I see it from a PBot dataset download?

**Comment by ecurrano** [comment]
Dori's comment 1 above is exactly what Andrew described in his initial comment.

Dori's comment 2 above is a good one, and perhaps something to discuss with Mark?

I'll add that in thinking about this more, I started thinking about recording quantitative traits (e.g. leaf size). In this case, we would want to assign it to an OTU without having to go through all the descriptive characters, but we might still want to record trait information particular to this specimen. Is this possible?

**Comment by aazaff** [comment]
Response to Dori
1. Yes, that's the idea.
2. I'm not sure it is true that we would not have a way to handle private specimens/entries in PBDB. We would have to discuss this with the PBDB side. It is certainly doable from a technical standpoint, but we'd need to coordinate it.
3. Yes, downloading PBDB items through pbot should be trivial.

Response to Ellen:
3. It would be possible the way I've been conceiving of it, but I think it might not the way Doug has. Let's raise this particular case next meeting.

**Comment by doricon** [comment]
1. sweet!
2. I worry that the PBDB board is going to ultimately be strict about the data that shows up on their side, especially regarding it needing to be for-real published. We should probably try to broach this soon so we can figure out how we will have to handle it! Hopefully it will be simple :) 
3. also sweet! 

Regarding quantitative characters: 
I've been mulling over this too. One way that seemed simple (at least in my head) is that for certain characters (ie the quant ones), entering a character state involves filling in two boxes: the value, and the specimen#/link the value belongs to. In this way, the workflow entry of quantitative data is still done through the OTU entry forms. A quant character can have many state entries, each one being a value+specimen. (really, for qualitative-ish characters like size category, this could be done too if the community so desires). 
-I would imagine that if doing it this way, when a user is creating a character/schema, a character can simply be defined as requiring a specimen number to support the state value. 
-By necessity, the specimens that are referred to in the state fields would be attached to the OTU as an occurrence of the OTU.
-Ultimately, I think this would prevent us needing to have an entry form/method for entering character data for specimens that is separate from the entry of data for OTUs. And also prevent the risk of having specimen character data floating around unattached to an OTU, which I think was mentioned at one point as a potential issue.
(apologies if some or all of this is already what y'all were thinking and I am just reiterating things!)

**Comment by aazaff** [comment]
Final decision:

1. Change the `:OTU` node label to `:Description`. They would have a property `type: "OTU"` or `type: "specimen"`

2. Queries on `:Description {type: "OTU}"` complexes would be of two types:
    1. `{type: "accepted")` - include only `:CharacterInstance` nodes that have `[DEFINED_BY]` relationships to the `Description` node
    2. `{type: "prospective"}` - include `:CharacterInstance` nodes that have both `[DEFINED_BY]` and `[CANDIDATE_FOR]` relationships to the `:Description` node

3. A `:Specimen` node will *always* have an `[EXAMPLE_OF]` relationship to a `:Description {type: "OTU"}` node. This `[EXAMPLE_OF]` 
    1. If this relationship was inferred, there will be an `{inferenceStatistic: "value"}` property containing a numeric value of a similarity index~~(might be JSON with subproperties specifying the comparison used and the the value)~~ 
    2. If this relationship was asserted, there will be no `{inferenceStatistic: "value"}` property in the ~~`[DESCRIBED_BY]`~~ `[EXAMPLE_OF]` relationship to a ~~`:Description {type: "specimen"}`~~ `:Description {type: "OTU"} node. ~~This relationship may not exist for an asserted specimen.~~

4. If a `:Specimen` node has an inferred `[EXAMPLE_OF]` relationship to a `:Description {type: "OTU"}`, then any of the `:CharacterInstance` nodes of its `Description {type: "specimen"}` complex that do not also exist in the `Description {type: "OTU"}` complex will have `[CANDIDATE_FOR]` relationships.

**Comment by aazaff** [comment]
> The following are clarifications to the specification for element **3.i** and **4**. 

3. A `:Specimen` node will *always* have an `[EXAMPLE_OF]` relationship to a `:Description {type: "OTU"}` node. 
    1. If this relationship was inferred, there will be an `{inferenceStatistic: "value"}` property containing a numeric value of a similarity index~~(might be JSON with subproperties specifying the comparison used and the the value)~~ ***I think graph databases do not support embedded JSON as properties. I also think it would make sense to make each individual metric its own property - e.g., `{bray-curtis: "value", jaccard: "value"}`***

4. If a `:Specimen` node has an inferred `[EXAMPLE_OF]` relationship to a `:Description {type: "OTU"}`, then any of the `:CharacterInstance` nodes of its `:Description {type: "specimen"}` complex that do not also exist in the `Description {type: "OTU"}` complex will have `[CANDIDATE_FOR]` relationships. ***This will only apply for*** `:Specimen` ***nodes that are attached to a*** `:Description {type: "specimen"}`.

**Comment by NoisyFlowers** [comment]
The changes required by the description above are in 5e87c10e01a2d2d58aaea6e8c12ef717871fd003,  1b47284e0da99c46737b6dacae8225932099f3f8, and be1b48220a5d7c42ae4acf77bf0845fc6810c8c0.
