### ISSUE TITLE
Start storing database dumps as cypher for easy reproduction

### ISSUE THREAD

**Issue by aazaff** [paleobot/pbot_client#13]

**Comment by NoisyFlowers** [comment]
Ok, so this works, but it's a bit of a pain. It wasn't straight-forward to figure out where everything is, but I think this covers it.

To export a db to a cypher file:
1) Find your database on disk. The easiest way to do this is to click the three dots for your db in the GUI, then click Terminal. This will open something that looks like a cmd shell on Windows and a bash shell on Ubuntu in the directory for your database. Copy this path.
2) Under that path is a conf directory. Go in there and add a file called apoc.conf with this line in it: 
```
apoc.export.file.enabled=true
```
3) Now start that db and open it in Neo4J Browser. Execute some version of this (details here: https://neo4j.com/labs/apoc/4.1/export/cypher/). This creates the file all.cypher in the import directory of your db:
```
CALL apoc.export.cypher.all("all.cypher", {
	format: "cypher-shell",
	useOptimizations: {type: "UNWIND_BATCH", unwindBatchSize: 20}
})
YIELD file, batches, source, format, nodes, relationships, properties, time, rows, batchSize
RETURN file, batches, source, format, nodes, relationships, properties, time, rows, batchSize;
```

To actually use this file to populate another db:
1) Create the db in Neo4J Desktop. Find it on disk, as in step (1) above.
2) In the conf directory, add a file called apoc.conf with this line:
```
apoc.import.file.enabled=true
```
3) Copy the all.cypher file from the import directory of the source database into the import directory of this new database.
4) Start the new db and open it in Neo4J Browser. Execute some version of this (some details here: https://neo4j.com/labs/apoc/4.1/cypher-execution/run-cypher-scripts/):
```
CALL apoc.cypher.runFile("all.cypher")
```
5) Verify that the db looks the way you expect.

I suppose what we should do is reorganize this repo. Maybe create an "initial_db_config" folder for the schema and otu cypher scripts, and a "db_backup" folder where we maintain this all.cypher file. The information in these folders will be redundant, but it won't hurt to have it in two forms.

**Comment by aazaff** [comment]
Yes, please! I would love to be able to spin up a copy that is approximately like what you have.

**Comment by NoisyFlowers** [comment]
Ok, this is more or less done now with 6128700a32502e2ddc50153d848482a70774cb6a. There were some changes before that, but the commit comment seems to have been swallowed by a merge (I'm going to have to get in the habit of explicit branching I guess).

There is nothing automated, but cypher/db_export/all.cypher should contain something like the latest at any given time.

**Comment by aazaff** [comment]
Just as an FYI, this take a LONG time to restore from. Not something we can fix, but thought I'd make a note of it.

**Comment by NoisyFlowers** [comment]
That's interesting. When I import the all.cypher file on my machine (Windows 10, i7, 16G), it is almost instant. I wonder what's different.

**Comment by aazaff** [comment]
I was just copy pasting the commands rather than following the import steps you outlined above. My fault.
