### ISSUE TITLE
Add instructions for some of the basic QUERIES to the readme

### ISSUE THREAD

**Issue by aazaff** [paleobot/pbot_client#14]
For example, what's the query to get an OTU complex? Just might be nice to have some starter queries handy in the documentation.

**Comment by NoisyFlowers** [comment]
In the short term, some of these can be found in scratch.cypher.

**Comment by NoisyFlowers** [comment]
Added a few handy ones in f310cd2f5f953bfca15ace2ddb23423a73b4a9df, 148bdb7361547a14936052f91eebe8105f13c665, and 2a3e336ab123f1bbcf0e117267f4bce533fcf55f.
