### ISSUE TITLE
Conflated "Schema" node with "Reference" node in sampledb.cql

### ISSUE THREAD

**Issue by aazaff** [paleobot/pbot_client#8]
Conceivably a schema may be built using several references. Schemas should be their own node.

**Comment by NoisyFlowers** [comment]
Are the author relationships on your current Reference nodes for those nodes, or would they be changed to the new Schema nodes?

**Comment by aazaff** [comment]
Good question.

I think in this case the authors would actually be applied to both as they authored both the publication (the book/manual) and authored/created the schema. It is possible (likely?) in future that authors of a reference won't be identical to schema authors though.

As a note, authors (whether for schemas or references) are distinct from enterers, as those are meant to indicate who literally entered it into the database.

Did that make sense?

**Comment by NoisyFlowers** [comment]
Can this be closed, based on how this is handled in sampledb2.cypher?

**Comment by aazaff** [comment]
Yeah totally fixed.
